package es.uji.al259348.sliwwebmanager.controllers;

import es.uji.al259348.sliwwebmanager.model.User;
import es.uji.al259348.sliwwebmanager.model.forms.UserForm;
import es.uji.al259348.sliwwebmanager.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.UUID;

@Controller
@RequestMapping(path = "users")
public class UsersController {

    @Autowired
    UserService userService;

    @RequestMapping
    public String list(Model model) {
        Iterable<User> users = userService.findAll();
        model.addAttribute("users", users);
        return "users/list";
    }

    @RequestMapping(path = "create")
    public String create(Model model) {

        String autoGeneratedId = UUID.randomUUID().toString();

        UserForm userForm = new UserForm();
        userForm.setId(autoGeneratedId);

        model.addAttribute("userCreateForm", userForm);

        return "users/create";
    }

    @RequestMapping(path = "create", method = RequestMethod.POST)
    public String create(@Valid UserForm userForm, BindingResult bindingResult) {

        if (bindingResult.hasErrors()) {
            return "users/create";
        }

        User user = userForm.getUser();
        System.out.println(user);

        userService.save(user);

        return "redirect:/users";
    }

}
